packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted
shamefullyHoist: true
strictPeerDependencies: false
autoInstallPeers: true
verifyDepsBeforeRun: false

allowBuilds:
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.16 || 57.0.18'
  - '@expo/config@57.0.8 || 57.0.9'
  - '@expo/fingerprint@0.20.8 || 0.20.10'
  - "@expo/inline-modules@0.1.6"
  - "@expo/log-box@57.0.3"
  - expo-asset@57.0.12 || 57.0.14
  - expo-constants@57.0.12 || 57.0.14
  - expo@57.0.14 || 57.0.16
  - expo-dev-client@57.0.13 || 57.0.15
  - expo-dev-launcher@57.0.13 || 57.0.15
  - expo-dev-menu@57.0.13 || 57.0.15
  - expo-updates@57.0.17
  - '@expo/config-plugins@57.0.9'
  - '@expo/image-utils@0.11.5'
  - '@expo/metro-config@57.0.10'
  - '@expo/metro-file-map@57.0.2'
  - '@expo/metro-runtime@57.0.13'
  - '@expo/prebuild-config@57.0.14'
  - '@expo/require-utils@57.0.5'
  - '@expo/ui@57.0.13'
  - babel-preset-expo@57.0.8
  - expo-auth-session@57.0.9
  - expo-crypto@57.0.2
  - expo-modules-autolinking@57.0.11
  - expo-modules-core@57.0.13
  - expo-router@57.0.16
  - expo-sharing@57.0.15
  - expo-splash-screen@57.0.8
